### ISSUE TITLE
About the calculation of recall and precision

### ISSUE THREAD

**Issue by BD-MF** [wcwowwwww/towe-eacl#1]
Is your evaluation index (computing precision/recall and f1) at the token level? I found out that recall and precision in your code (def IE_score(self, y, pred)) are calculated incorrectly (on the contrary), and the baseline models in your paper use span-level evaluation indicators. Is this reasonable?

**Comment by AnWang-AI** [comment]
Thank you for your question. The evaluation is based on span-level as other previous work did.
